apiVersion: v1
kind: Service
metadata:
  name: ccommander-nip
  labels:
    app: ccommander
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8000
      nodePort: 31081
      name: http
  selector:
    app: ccommander
