apiVersion: v1
kind: Service
metadata:
  name: ccommander-nip
  labels:
    app: ccommander
spec:
  selector:
    app: ccommander
  type: NodePort
  ports:
  - name: http
    port: 8081
    targetPort: 8000
    nodePort: 31081
